export const completeArchivedVisits: Visit[] = [
  {
    id: "62",
    nom: "STREAM",
    congregation: "À définir",
    telephone: "",
    visitId: "2d6df9e8-97f4-4310-909c-6fce1b4ea882",
    visitDate: "2025-09-13",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "streaming",
    talkNoOrType: "43",
    talkTheme: "Kel ki Deus ta fla sénpri é midjór pa nos",
    communicationStatus: {},
  },
  {
    id: "62",
    nom: "STREAM",
    congregation: "À définir",
    telephone: "",
    visitId: "65159ae2-e241-4cb7-8d9e-948bd8a1678a",
    visitDate: "2025-10-11",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "streaming",
    talkNoOrType: "5",
    talkTheme: "Kuzê ki ta djuda bu família ser filís?",
    communicationStatus: {},
  },
  {
    id: "58",
    nom: "Dimitri GIVAC",
    congregation: "Marseille KBV",
    telephone: "",
    visitId: "cb05cac9-9d8e-4178-ad8e-937f918d06b3",
    visitDate: "2025-10-18",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: null,
    talkTheme: null,
    communicationStatus: {},
  },
  {
    id: "33",
    nom: "Moises CALDES",
    congregation: "Cannes KBV",
    telephone: "33627826869",
    visitId: "4c4cbb79-24cc-4c3f-9c0b-607c10bdf6f5",
    visitDate: "2025-10-11",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "183",
    talkTheme: "Tra odju di kuzas ki ka ten valor!",
    communicationStatus: {},
  },
  {
    id: "ccd3ae55-ae6e-44cd-ab57-be07691751ee",
    nom: "Ricardo PASCOAL",
    congregation: "Streaming",
    telephone: "",
    visitId: "496b8a04-9918-4f42-9aaa-d9e41b0ad339",
    visitDate: "2025-10-11",
    visitTime: "14:30",
    host: "N/A",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "streaming",
    talkNoOrType: "5",
    talkTheme: null,
    communicationStatus: {},
  },
  {
    id: "b6bb602e-dc9d-4750-af29-8a61831b79cc",
    nom: "Mario MIRANDA",
    congregation: "Cannes KBV Zoom",
    telephone: "33615879709",
    visitId: "9a4b263d-0daa-4560-8eb4-bdf7167cee83",
    visitDate: "2025-10-25",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "zoom",
    talkNoOrType: "100",
    talkTheme: "Modi ki nu pode faze bons amizadi",
    communicationStatus: {},
  },
  {
    id: "16",
    nom: "Isaque PEREIRA",
    congregation: "St Denis KBV",
    telephone: "33652851904",
    visitId: "visit-16-2024-02-18",
    visitDate: "2024-02-18",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "50",
    talkTheme: "Modi ki nu pode toma disizons ki ta djuda-nu ten bons rezultadu na vida",
    communicationStatus: {},
  },
  {
    id: "33",
    nom: "Moises CALDES",
    congregation: "Cannes KBV",
    telephone: "33627826869",
    visitId: "visit-33-2024-11-17",
    visitDate: "2024-11-17",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "64",
    talkTheme: "Bu 'krê sô pasa sábi' ô bu ta 'ama Deus'?",
    communicationStatus: {},
  },
  {
    id: "10",
    nom: "David VIEIRA",
    congregation: "Villiers KBV",
    telephone: "33771670140",
    visitId: "visit-10-2024-05-26",
    visitDate: "2024-05-26",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "48",
    talkTheme: "Modi ki nu pode kontinua lial pa Deus óras ki nu ta pasa pa próva",
    communicationStatus: {},
  },
  {
    id: "6",
    nom: "Dany TAVARES",
    congregation: "Plaisir KBV",
    telephone: "33668121101",
    visitId: "1edb49d2-ead2-49ad-8d58-088ec3f1a9ef",
    visitDate: "2025-09-20",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "102",
    talkTheme: "Presta atenson na "profesia"",
    communicationStatus: {},
  },
  {
    id: "21",
    nom: "João-Paulo BAPTISTA",
    congregation: "Lyon KBV",
    telephone: "33611234567",
    visitId: "84edc96a-4869-4ef2-a47d-2956da704679",
    visitDate: "2025-09-27",
    visitTime: "14:30",
    host: "N/A",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "DS",
    talkTheme: "Modi ki géra ta ben kaba ?",
    communicationStatus: {},
  },
  {
    id: "63",
    nom: "Rémy CAPELA",
    congregation: "À définir",
    telephone: "",
    visitId: "visit-63-2023-12-18",
    visitDate: "2023-12-18",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "26",
    talkTheme: "Abo é inportanti pa Deus?",
    communicationStatus: {},
  },
  {
    id: "81ee3039-4399-44b9-aeaa-e1331d069e41",
    nom: "Gianni FARIA",
    congregation: "Plaisir KBV",
    telephone: "33698657173",
    visitId: "782e566c-5990-4e4e-b913-53884d9a498b",
    visitDate: "2025-11-08",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "26",
    talkTheme: null,
    communicationStatus: {},
  },
  {
    id: "85936cd3-4ccc-41aa-9558-0fb2fe14eb5c",
    nom: "Dimitri GIVAC",
    congregation: "Marseille KBV",
    telephone: "",
    visitId: "cb05cac9-9d8e-4178-ad8e-937f918d06b3",
    visitDate: "2025-10-18",
    visitTime: "14:30",
    host: "À définir",
    accommodation: "",
    meals: "",
    status: "completed",
    locationType: "physical",
    talkNoOrType: "3",
    talkTheme: null,
    communicationStatus: {},
  },
];
